{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# FastAPI - Building fast and scalable REST APIs with Python\n",
    "\n",
    "*COPYRIGHT NOTICE: Parts of this tutorial are from the (amazing) [fastapi docs](fastapi.tiangolo.com)*.\n",
    "\n",
    "*FastAPI is a modern, fast (high-performance), web framework for building APIs with Python based on standard Python type hints.*\n",
    "\n",
    "As data scientists we usually build models that are trained on data and optimised on some metrics. At some point, a model needs to be integrated into existing processes, systems and applications. One way to do this is build a microservice that is running inference. FastAPI is a framework that will help us to build a quick REST API that can be integrated into the existing enterprise landscape. "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## What is a REST API?\n",
    "If REST APIs are new to you, feel free to read this article [API Guide for Data Scientists](https://www.enjoyalgorithms.com/blog/api-introduction-for-data-science-and-ml).\n",
    "\n",
    "An API is a set of protocols, routines, tools, and standards that **enable software applications to communicate with each other**. In other words, an API defines how software components should interact with each other and provides a way for developers to access the functionality of a particular application or service, without having to understand the underlying code.\n",
    "\n",
    "A **REST API** (Representational State Transfer Application Programming Interface) is a set of rules that allows different applications to communicate over the web using standard HTTP methods like GET, POST, PUT, and DELETE. For data scientists, it provides a way to access and manipulate data from remote servers, enabling seamless integration of data sources and machine learning models into their workflows."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Why is FastAPI a great choice for inference?\n",
    "- **Fast**: Very high performance, on par with NodeJS and Go (thanks to Starlette and Pydantic).\n",
    "- **Huge productivity**: It's very fast to code with FastAPI. In the docs they say the following: *Increase the speed to develop features by about 200% to 300%.*\n",
    "- **Fewer bugs**: Reduce about 40% of human (developer) induced errors.\n",
    "- **Intuitive**: Great editor support. Completion everywhere. Less time debugging.\n",
    "- **Easy**: Designed to be easy to use and learn. Less time reading docs.\n",
    "- **Short**: Minimize code duplication. Multiple features from each parameter declaration. Fewer bugs.\n",
    "- **Robust**: Get production-ready code. With automatic interactive documentation.\n",
    "- **Standards-based**: Based on (and fully compatible with) the open standards for APIs: OpenAPI (previously known as Swagger) and JSON Schema."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## What does an API built with FastAPI look like?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%writefile fastapi_example.py\n",
    "from fastapi import FastAPI\n",
    "\n",
    "# FastAPI provides all the functionality for your API.\n",
    "app = FastAPI()\n",
    "\n",
    "\n",
    "# this python function is decorated with a function called `get` provided by the FastAPI object.\n",
    "# it defines a HTTP GET operation in the root path\n",
    "@app.get(\"/\")\n",
    "def root():\n",
    "    return {\"Hello\": \"World\"}\n",
    "\n",
    "\n",
    "# this GET operation retrieves an item_id from the URL path and an optional query parameter 'q'\n",
    "@app.get(\"/items/{item_id}\")\n",
    "def echo_item(item_id: int, q: str | None = None):\n",
    "    return {\"item_id\": item_id, \"q\": q}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!fastapi dev fastapi_example.py --port 7777 --host 0.0.0.0"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Declarative Request and Response Bodies with Pydantic\n",
    "\n",
    "When you need to send data from a client to your API, you send it as a request body. A request body is data sent by the client to your API. A response body is the data your API sends to the client.\n",
    "\n",
    "We can use the library `pydantic` to declare bodies as python classes. FastAPI will be able to parse them correctly."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%writefile fastapi_example_with_pydantic.py\n",
    "from fastapi import FastAPI\n",
    "from pydantic import BaseModel\n",
    "\n",
    "app = FastAPI()\n",
    "\n",
    "# declare the participant structure by inheriting from BaseModel\n",
    "class Participant(BaseModel):\n",
    "    first_name: str \n",
    "    surname: str\n",
    "    age: int\n",
    "    pets: list[str] | None = None\n",
    "\n",
    "# In-memory list to store participants. In a rela application, this would be a sql database, probably\n",
    "participants = []\n",
    "\n",
    "# POST operation to add a new participant\n",
    "@app.post(\"/participants/\")\n",
    "def add_participant(participant: Participant):\n",
    "    participants.append(participant)\n",
    "    return {\"message\": \"Participant added successfully\", \"participant\": participant}\n",
    "\n",
    "# GET operation to get all participants\n",
    "@app.get(\"/participants/\")\n",
    "def get_participants() -> list[Participant]:\n",
    "    return participants"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!fastapi dev fastapi_example_with_pydantic.py --port 7778 --host 0.0.0.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34mINFO    \u001b[0m Using path \u001b[34mtodo.py\u001b[0m                                                     \n",
      "\u001b[34mINFO    \u001b[0m Resolved absolute path \u001b[35m/workshop/notebooks/fastapi/\u001b[0m\u001b[95mtodo.py\u001b[0m             \n",
      "\u001b[34mINFO    \u001b[0m Searching for package file structure from directories with \u001b[34m__init__.py\u001b[0m \n",
      "         files                                                                  \n",
      "\u001b[34mINFO    \u001b[0m Importing from \u001b[35m/workshop/notebooks/\u001b[0m\u001b[95mfastapi\u001b[0m                             \n",
      "                                                                                \n",
      " ╭─ \u001b[1;32mPython module file\u001b[0m ─╮                                                       \n",
      " │                      │                                                       \n",
      " │  🐍 todo.py          │                                                       \n",
      " │                      │                                                       \n",
      " ╰──────────────────────╯                                                       \n",
      "                                                                                \n",
      "\u001b[34mINFO    \u001b[0m Importing module \u001b[32mtodo\u001b[0m                                                  \n",
      "\u001b[34mINFO    \u001b[0m Found importable FastAPI app                                           \n",
      "                                                                                \n",
      " ╭─ \u001b[1;32mImportable FastAPI app\u001b[0m ─╮                                                   \n",
      " │                          │                                                   \n",
      " │  \u001b[91;40mfrom\u001b[0m\u001b[97;40m \u001b[0m\u001b[97;40mtodo\u001b[0m\u001b[97;40m \u001b[0m\u001b[91;40mimport\u001b[0m\u001b[97;40m \u001b[0m\u001b[97;40mapi\u001b[0m\u001b[40m  \u001b[0m  │                                                   \n",
      " │                          │                                                   \n",
      " ╰──────────────────────────╯                                                   \n",
      "                                                                                \n",
      "\u001b[34mINFO    \u001b[0m Using import string \u001b[1;32mtodo:api\u001b[0m                                           \n",
      "                                                                                \n",
      " \u001b[30;43m╭─\u001b[0m\u001b[30;43m─────────\u001b[0m FastAPI CLI - Development mode \u001b[30;43m──────────\u001b[0m\u001b[30;43m─╮\u001b[0m                        \n",
      " \u001b[30;43m│\u001b[0m\u001b[30;43m                                                     \u001b[0m\u001b[30;43m│\u001b[0m                        \n",
      " \u001b[30;43m│\u001b[0m\u001b[30;43m  \u001b[0m\u001b[2;30;43mServing at:\u001b[0m\u001b[30;43m \u001b[0m\u001b[30;43mhttp://0.0.0.0:7777\u001b[0m\u001b[30;43m                  \u001b[0m\u001b[30;43m  \u001b[0m\u001b[30;43m│\u001b[0m                        \n",
      " \u001b[30;43m│\u001b[0m\u001b[30;43m  \u001b[0m\u001b[30;43m                                                 \u001b[0m\u001b[30;43m  \u001b[0m\u001b[30;43m│\u001b[0m                        \n",
      " \u001b[30;43m│\u001b[0m\u001b[30;43m  \u001b[0m\u001b[2;30;43mAPI docs:\u001b[0m\u001b[30;43m \u001b[0m\u001b[30;43mhttp://0.0.0.0:7777/docs\u001b[0m\u001b[30;43m               \u001b[0m\u001b[30;43m  \u001b[0m\u001b[30;43m│\u001b[0m                        \n",
      " \u001b[30;43m│\u001b[0m\u001b[30;43m  \u001b[0m\u001b[30;43m                                                 \u001b[0m\u001b[30;43m  \u001b[0m\u001b[30;43m│\u001b[0m                        \n",
      " \u001b[30;43m│\u001b[0m\u001b[30;43m  \u001b[0m\u001b[2;30;43mRunning in development mode, for production use:\u001b[0m\u001b[30;43m \u001b[0m\u001b[30;43m  \u001b[0m\u001b[30;43m│\u001b[0m                        \n",
      " \u001b[30;43m│\u001b[0m\u001b[30;43m  \u001b[0m\u001b[30;43m                                                 \u001b[0m\u001b[30;43m  \u001b[0m\u001b[30;43m│\u001b[0m                        \n",
      " \u001b[30;43m│\u001b[0m\u001b[30;43m  \u001b[0m\u001b[1;30;43mfastapi run\u001b[0m\u001b[30;43m                                      \u001b[0m\u001b[30;43m  \u001b[0m\u001b[30;43m│\u001b[0m                        \n",
      " \u001b[30;43m│\u001b[0m\u001b[30;43m                                                     \u001b[0m\u001b[30;43m│\u001b[0m                        \n",
      " \u001b[30;43m╰─────────────────────────────────────────────────────╯\u001b[0m                        \n",
      "                                                                                \n",
      "\u001b[32mINFO\u001b[0m:     Will watch for changes in these directories: ['/workshop/notebooks/fastapi']\n",
      "\u001b[32mINFO\u001b[0m:     Uvicorn running on \u001b[1mhttp://0.0.0.0:7777\u001b[0m (Press CTRL+C to quit)\n",
      "\u001b[32mINFO\u001b[0m:     Started reloader process [\u001b[36m\u001b[1m1017\u001b[0m] using \u001b[36m\u001b[1mWatchFiles\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1041\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:61844 - \"\u001b[1mGET /docs HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:61844 - \"\u001b[1mGET /openapi.json HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:65146 - \"\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" \u001b[91m500 Internal Server Error\u001b[0m\n",
      "\u001b[31mERROR\u001b[0m:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py\", line 401, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 301, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 214, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/concurrency.py\", line 39, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/to_thread.py\", line 56, in run_sync\n",
      "    return await get_async_backend().run_sync_in_worker_thread(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 2441, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 943, in run\n",
      "    result = context.run(func, *args)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/workshop/notebooks/fastapi/todo.py\", line 65, in post_predict\n",
      "    labels, probabilities = sess.run(None, ins)\n",
      "                            ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py\", line 216, in run\n",
      "    self._validate_input(list(input_feed.keys()))\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py\", line 198, in _validate_input\n",
      "    raise ValueError(\n",
      "ValueError: Required inputs (['married', 'dependents', 'education', 'self_employed', 'property_area', 'coapplicantincome', 'loanamount', 'loan_amount_term', 'credit_history']) are missing from input feed (['applicantincome']).\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in '.ipynb_checkpoints/todo-checkpoint.py', 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1041\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1077\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:60064 - \"\u001b[1mGET /docs HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:60064 - \"\u001b[1mGET /openapi.json HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:60064 - \"\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" \u001b[91m500 Internal Server Error\u001b[0m\n",
      "\u001b[31mERROR\u001b[0m:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py\", line 401, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 301, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 214, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/concurrency.py\", line 39, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/to_thread.py\", line 56, in run_sync\n",
      "    return await get_async_backend().run_sync_in_worker_thread(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 2441, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 943, in run\n",
      "    result = context.run(func, *args)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/workshop/notebooks/fastapi/todo.py\", line 71, in post_predict\n",
      "    predicted.append(Prediction(label=k, probability=v))\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/pydantic/main.py\", line 212, in __init__\n",
      "    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "pydantic_core._pydantic_core.ValidationError: 1 validation error for Prediction\n",
      "label\n",
      "  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='N', input_type=str]\n",
      "    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in '.ipynb_checkpoints/todo-checkpoint.py', 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1077\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1121\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in '.ipynb_checkpoints/todo-checkpoint.py', 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1121\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1159\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:58288 - \"\u001b[1mGET /docs HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:58288 - \"\u001b[1mGET /openapi.json HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:58288 - \"\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" \u001b[91m500 Internal Server Error\u001b[0m\n",
      "\u001b[31mERROR\u001b[0m:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py\", line 401, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 301, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 214, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/concurrency.py\", line 39, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/to_thread.py\", line 56, in run_sync\n",
      "    return await get_async_backend().run_sync_in_worker_thread(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 2441, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 943, in run\n",
      "    result = context.run(func, *args)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/workshop/notebooks/fastapi/todo.py\", line 69, in post_predict\n",
      "    predicted.append(Prediction(label=k, probability=v))\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/pydantic/main.py\", line 212, in __init__\n",
      "    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "pydantic_core._pydantic_core.ValidationError: 1 validation error for Prediction\n",
      "label\n",
      "  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='N', input_type=str]\n",
      "    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in '.ipynb_checkpoints/todo-checkpoint.py', 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1159\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1219\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in '.ipynb_checkpoints/todo-checkpoint.py', 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1219\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1245\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:60608 - \"\u001b[1mGET /docs HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:60608 - \"\u001b[1mGET /openapi.json HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "['N'] [{'N': 0.8638753294944763, 'Y': 0.13612467050552368}]\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:60608 - \"\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in '.ipynb_checkpoints/todo-checkpoint.py', 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1245\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1279\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:64422 - \"\u001b[1mGET /docs HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:64422 - \"\u001b[1mGET /openapi.json HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:64422 - \"\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in '.ipynb_checkpoints/todo-checkpoint.py', 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1279\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1307\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:59276 - \"\u001b[1mGET /docs HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:59276 - \"\u001b[1mGET /openapi.json HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:59276 - \"\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" \u001b[91m500 Internal Server Error\u001b[0m\n",
      "\u001b[31mERROR\u001b[0m:    Exception in ASGI application\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py\", line 401, in run_asgi\n",
      "    result = await app(  # type: ignore[func-returns-value]\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n",
      "    return await self.app(scope, receive, send)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/applications.py\", line 1054, in __call__\n",
      "    await super().__call__(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/applications.py\", line 113, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 187, in __call__\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 165, in __call__\n",
      "    await self.app(scope, receive, _send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n",
      "    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 715, in __call__\n",
      "    await self.middleware_stack(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 735, in app\n",
      "    await route.handle(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 288, in handle\n",
      "    await self.app(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 76, in app\n",
      "    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n",
      "    raise exc\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n",
      "    await app(scope, receive, sender)\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 73, in app\n",
      "    response = await f(request)\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 301, in app\n",
      "    raw_response = await run_endpoint_function(\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 214, in run_endpoint_function\n",
      "    return await run_in_threadpool(dependant.call, **values)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/starlette/concurrency.py\", line 39, in run_in_threadpool\n",
      "    return await anyio.to_thread.run_sync(func, *args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/to_thread.py\", line 56, in run_sync\n",
      "    return await get_async_backend().run_sync_in_worker_thread(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 2441, in run_sync_in_worker_thread\n",
      "    return await future\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 943, in run\n",
      "    result = context.run(func, *args)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/workshop/notebooks/fastapi/todo.py\", line 63, in post_predict\n",
      "    labels, probabilities = sess.run(None, ins)\n",
      "                            ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/pysetup/.venv/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py\", line 220, in run\n",
      "    return self._sess.run(output_names, input_feed, run_options)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(float))\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in '.ipynb_checkpoints/todo-checkpoint.py', 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1307\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1337\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:62166 - \"\u001b[1mGET /docs HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:62166 - \"\u001b[1mGET /openapi.json HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[32mINFO\u001b[0m:     172.20.0.1:62166 - \"\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" \u001b[32m200 OK\u001b[0m\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1337\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1490\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1490\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Started server process [\u001b[36m1514\u001b[0m]\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application startup.\n",
      "\u001b[32mINFO\u001b[0m:     Application startup complete.\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in 'solution.py', '.ipynb_checkpoints/todo-checkpoint.py', '.ipynb_checkpoints/solution-checkpoint.py', 'todo.py'. Reloading...\n",
      "\u001b[32mINFO\u001b[0m:     Shutting down\n",
      "\u001b[32mINFO\u001b[0m:     Waiting for application shutdown.\n",
      "\u001b[32mINFO\u001b[0m:     Application shutdown complete.\n",
      "\u001b[32mINFO\u001b[0m:     Finished server process [\u001b[36m1514\u001b[0m]\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in 'solution.py', '.ipynb_checkpoints/solution-checkpoint.py'. Reloading...\n",
      "\u001b[31mERROR\u001b[0m:    Error loading ASGI app. Could not import module \"todo\".\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in 'solution.py', '.ipynb_checkpoints/solution-checkpoint.py'. Reloading...\n",
      "\u001b[31mERROR\u001b[0m:    Error loading ASGI app. Could not import module \"todo\".\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in 'solution.py', '.ipynb_checkpoints/solution-checkpoint.py'. Reloading...\n",
      "\u001b[31mERROR\u001b[0m:    Error loading ASGI app. Could not import module \"todo\".\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in 'solution-Copy1.py'. Reloading...\n",
      "\u001b[31mERROR\u001b[0m:    Error loading ASGI app. Could not import module \"todo\".\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in 'solution-Copy1.py'. Reloading...\n",
      "\u001b[31mERROR\u001b[0m:    Error loading ASGI app. Could not import module \"todo\".\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in 'onnx_exercise.py', 'solution-Copy1.py'. Reloading...\n",
      "\u001b[31mERROR\u001b[0m:    Error loading ASGI app. Could not import module \"todo\".\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in '.ipynb_checkpoints/onnx_exercise-checkpoint.py'. Reloading...\n",
      "\u001b[31mERROR\u001b[0m:    Error loading ASGI app. Could not import module \"todo\".\n",
      "\u001b[33mWARNING\u001b[0m:  WatchFiles detected changes in 'onnx_exercise.py', '.ipynb_checkpoints/onnx_exercise-checkpoint.py'. Reloading...\n",
      "\u001b[31mERROR\u001b[0m:    Error loading ASGI app. Could not import module \"todo\".\n"
     ]
    }
   ],
   "source": [
    "!fastapi dev todo.py --port 7777 --host 0.0.0.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
