services:
  jupyter:
    image: codecentric/from-jupyter-to-production-jupyter:latest
    ports:
      - 8888:8888
      - 4141:4141
      - 7777:7777
    volumes:
      - type: bind
        source: ./notebooks
        target: /workshop/notebooks
      - workspace:/workshop/workspace
      - type: bind
        source: ./data/dagster
        target: /workshop/notebooks/dagster/data
      - type: bind
        source: ./data/dagster
        target: /workshop/notebooks/mlflow/data
      - type: bind
        source: ./data/mlflow
        target: /workshop/notebooks/mlflow/data/mlflow
      - type: bind
        source: ./data/dagster
        target: /workshop/notebooks/solutions/data
      - type: bind
        source: ./data/mlflow
        target: /workshop/notebooks/solutions/data/mlflow
      - type: bind
        source: ./data/dvc
        target: /workshop/notebooks/dvc/data
    links:
      - "mlflow:mlflow"
  mlflow:
    image: codecentric/from-jupyter-to-production-mlflow:latest
    ports:
      - 5001:5001
    volumes:
      - workspace:/ml_data
  dagster:
    image: codecentric/from-jupyter-to-production-dagster
    ports:
      - 3000:3000
    entrypoint: "dagster dev  -h 0.0.0.0 -p 3000 -f ./scripts/dagster_exercise_assets_job.py -f ./scripts/dagster_exercise_ops_job.py -f ./scripts/dagster_exercise_ops_job_mlflow.py"

    volumes:
      - type: bind
        source: ./notebooks/dagster/scripts/
        target: /opt/dagster/app/scripts
      - type: bind
        source: ./data/dagster
        target: /opt/dagster/app/data

    # disable logging since the startup will (rightfully) complain about incorrect syntax
    attach: false

volumes:
  workspace:
